fn = input("Enter First name: ")
ln = input("Enter Last name: ")
mn = input("Enter Middle name: ")
bd = input("Enter Birthday: ")
g = input("Enter Gender: ")
add = input("Enter Address: ")
crs = input("Enter Course: ")
yl = input("Enter Year Level: ")
print("First name:", fn)
print("Middle name:", mn)
print("Last name:", ln)
print("Birthday:", bd)
print("Gender:", g)
print("Address:", add)
print("Course:", crs)
print("Year Level:", yl)